name: dart_task_manager
description: by gatovo labs

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_datetime_picker: ^1.5.1
  intl: 0.17.0
  hive: 2.0.4
  path_provider: 2.0.2
  hive_flutter: ^1.1.0
  enum_to_string: ^2.0.1
  cupertino_icons: ^1.0.0
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  firebase_core: 1.3.0
  firebase_auth: 2.0.0
  cloud_firestore: 2.3.0
  firebase_database: 7.1.1
  connectivity_plus: ^1.0.6
  flutter_staggered_animations: ^1.0.0
  flutter_speed_dial: ^4.2.0

flutter_native_splash:
  color: "#2B2B2B"
  image: "assets/images/SPLASH.png"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/ICON.png"
  #adaptive_icon_foreground: "assets/icon/test.png"
  adaptive_icon_background: "#FFFFFF"
  #adaptive_icon_padding: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.0
  build_runner: 2.0.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/SPLASH.png

#flutter pub run flutter_launcher_icons:main
#flutter pub run flutter_native_splash:create